/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package board;

/**
 *
 * @author Lenovo
 */
public class Tablero_1 extends javax.swing.JFrame {

    /**
     * Creates new form interfaz1
     */
    public Tablero_1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        vistatablero = new javax.swing.JPanel();
        c00 = new javax.swing.JButton();
        c01 = new javax.swing.JButton();
        c02 = new javax.swing.JButton();
        c03 = new javax.swing.JButton();
        c04 = new javax.swing.JButton();
        c05 = new javax.swing.JButton();
        c06 = new javax.swing.JButton();
        c07 = new javax.swing.JButton();
        c10 = new javax.swing.JButton();
        c11 = new javax.swing.JButton();
        c12 = new javax.swing.JButton();
        c13 = new javax.swing.JButton();
        c14 = new javax.swing.JButton();
        c15 = new javax.swing.JButton();
        c16 = new javax.swing.JButton();
        c17 = new javax.swing.JButton();
        c20 = new javax.swing.JButton();
        c21 = new javax.swing.JButton();
        c22 = new javax.swing.JButton();
        c23 = new javax.swing.JButton();
        c24 = new javax.swing.JButton();
        c25 = new javax.swing.JButton();
        c26 = new javax.swing.JButton();
        c27 = new javax.swing.JButton();
        c30 = new javax.swing.JButton();
        c31 = new javax.swing.JButton();
        c32 = new javax.swing.JButton();
        c33 = new javax.swing.JButton();
        c34 = new javax.swing.JButton();
        c35 = new javax.swing.JButton();
        c36 = new javax.swing.JButton();
        c37 = new javax.swing.JButton();
        c40 = new javax.swing.JButton();
        c41 = new javax.swing.JButton();
        c42 = new javax.swing.JButton();
        c43 = new javax.swing.JButton();
        c44 = new javax.swing.JButton();
        c45 = new javax.swing.JButton();
        c46 = new javax.swing.JButton();
        c47 = new javax.swing.JButton();
        c50 = new javax.swing.JButton();
        c51 = new javax.swing.JButton();
        c52 = new javax.swing.JButton();
        c53 = new javax.swing.JButton();
        c54 = new javax.swing.JButton();
        c55 = new javax.swing.JButton();
        c56 = new javax.swing.JButton();
        c57 = new javax.swing.JButton();
        c60 = new javax.swing.JButton();
        c61 = new javax.swing.JButton();
        c62 = new javax.swing.JButton();
        c63 = new javax.swing.JButton();
        c64 = new javax.swing.JButton();
        c65 = new javax.swing.JButton();
        c66 = new javax.swing.JButton();
        c67 = new javax.swing.JButton();
        c70 = new javax.swing.JButton();
        c71 = new javax.swing.JButton();
        c72 = new javax.swing.JButton();
        c73 = new javax.swing.JButton();
        c74 = new javax.swing.JButton();
        c75 = new javax.swing.JButton();
        c76 = new javax.swing.JButton();
        c77 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        vistatablero.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        vistatablero.setPreferredSize(new java.awt.Dimension(576, 576));
        vistatablero.setLayout(new java.awt.GridLayout(8, 8));

        c00.setBackground(new java.awt.Color(255, 255, 255));
        c00.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/TorreNegra-removebg-preview.png"))); // NOI18N
        c00.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        c00.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c00ActionPerformed(evt);
            }
        });
        vistatablero.add(c00);

        c01.setBackground(new java.awt.Color(102, 102, 102));
        c01.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/CaballoNegro-removebg-preview.png"))); // NOI18N
        c01.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        c01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c01ActionPerformed(evt);
            }
        });
        vistatablero.add(c01);

        c02.setBackground(new java.awt.Color(255, 255, 255));
        c02.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/AlfilNegro-removebg-preview (2).png"))); // NOI18N
        c02.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        c02.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c02ActionPerformed(evt);
            }
        });
        vistatablero.add(c02);

        c03.setBackground(new java.awt.Color(102, 102, 102));
        c03.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ReinaNegra-removebg-preview.png"))); // NOI18N
        c03.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        c03.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c03ActionPerformed(evt);
            }
        });
        vistatablero.add(c03);

        c04.setBackground(new java.awt.Color(255, 255, 255));
        c04.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ReyNegro-removebg-preview.png"))); // NOI18N
        c04.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        c04.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c04ActionPerformed(evt);
            }
        });
        vistatablero.add(c04);

        c05.setBackground(new java.awt.Color(102, 102, 102));
        c05.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/AlfilNegro-removebg-preview (2).png"))); // NOI18N
        c05.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        c05.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c05ActionPerformed(evt);
            }
        });
        vistatablero.add(c05);

        c06.setBackground(new java.awt.Color(255, 255, 255));
        c06.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/CaballoNegro-removebg-preview.png"))); // NOI18N
        c06.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        c06.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c06ActionPerformed(evt);
            }
        });
        vistatablero.add(c06);

        c07.setBackground(new java.awt.Color(102, 102, 102));
        c07.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/TorreNegra-removebg-preview.png"))); // NOI18N
        c07.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        c07.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c07ActionPerformed(evt);
            }
        });
        vistatablero.add(c07);

        c10.setBackground(new java.awt.Color(102, 102, 102));
        c10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Ficha_PeonNegra-removebg-preview.png"))); // NOI18N
        c10.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        vistatablero.add(c10);

        c11.setBackground(new java.awt.Color(255, 255, 255));
        c11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Ficha_PeonNegra-removebg-preview.png"))); // NOI18N
        c11.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        c11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c11ActionPerformed(evt);
            }
        });
        vistatablero.add(c11);

        c12.setBackground(new java.awt.Color(102, 102, 102));
        c12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Ficha_PeonNegra-removebg-preview.png"))); // NOI18N
        c12.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        vistatablero.add(c12);

        c13.setBackground(new java.awt.Color(255, 255, 255));
        c13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Ficha_PeonNegra-removebg-preview.png"))); // NOI18N
        c13.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        vistatablero.add(c13);

        c14.setBackground(new java.awt.Color(102, 102, 102));
        c14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Ficha_PeonNegra-removebg-preview.png"))); // NOI18N
        c14.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        c14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c14ActionPerformed(evt);
            }
        });
        vistatablero.add(c14);

        c15.setBackground(new java.awt.Color(255, 255, 255));
        c15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Ficha_PeonNegra-removebg-preview.png"))); // NOI18N
        c15.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        vistatablero.add(c15);

        c16.setBackground(new java.awt.Color(102, 102, 102));
        c16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Ficha_PeonNegra-removebg-preview.png"))); // NOI18N
        c16.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        vistatablero.add(c16);

        c17.setBackground(new java.awt.Color(255, 255, 255));
        c17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Ficha_PeonNegra-removebg-preview.png"))); // NOI18N
        c17.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        vistatablero.add(c17);

        c20.setBackground(new java.awt.Color(255, 255, 255));
        c20.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        c20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c20ActionPerformed(evt);
            }
        });
        vistatablero.add(c20);

        c21.setBackground(new java.awt.Color(102, 102, 102));
        c21.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        c21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c21ActionPerformed(evt);
            }
        });
        vistatablero.add(c21);

        c22.setBackground(new java.awt.Color(255, 255, 255));
        c22.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        vistatablero.add(c22);

        c23.setBackground(new java.awt.Color(102, 102, 102));
        c23.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        vistatablero.add(c23);

        c24.setBackground(new java.awt.Color(255, 255, 255));
        c24.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        c24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c24ActionPerformed(evt);
            }
        });
        vistatablero.add(c24);

        c25.setBackground(new java.awt.Color(102, 102, 102));
        c25.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        vistatablero.add(c25);

        c26.setBackground(new java.awt.Color(255, 255, 255));
        c26.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        vistatablero.add(c26);

        c27.setBackground(new java.awt.Color(102, 102, 102));
        c27.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        vistatablero.add(c27);

        c30.setBackground(new java.awt.Color(102, 102, 102));
        c30.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        vistatablero.add(c30);

        c31.setBackground(new java.awt.Color(255, 255, 255));
        c31.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        vistatablero.add(c31);

        c32.setBackground(new java.awt.Color(102, 102, 102));
        c32.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        vistatablero.add(c32);

        c33.setBackground(new java.awt.Color(255, 255, 255));
        c33.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        vistatablero.add(c33);

        c34.setBackground(new java.awt.Color(102, 102, 102));
        c34.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        vistatablero.add(c34);

        c35.setBackground(new java.awt.Color(255, 255, 255));
        c35.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        vistatablero.add(c35);

        c36.setBackground(new java.awt.Color(102, 102, 102));
        c36.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        vistatablero.add(c36);

        c37.setBackground(new java.awt.Color(255, 255, 255));
        c37.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        vistatablero.add(c37);

        c40.setBackground(new java.awt.Color(255, 255, 255));
        c40.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        c40.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c40ActionPerformed(evt);
            }
        });
        vistatablero.add(c40);

        c41.setBackground(new java.awt.Color(102, 102, 102));
        c41.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        vistatablero.add(c41);

        c42.setBackground(new java.awt.Color(255, 255, 255));
        c42.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        vistatablero.add(c42);

        c43.setBackground(new java.awt.Color(102, 102, 102));
        c43.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        vistatablero.add(c43);

        c44.setBackground(new java.awt.Color(255, 255, 255));
        c44.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        vistatablero.add(c44);

        c45.setBackground(new java.awt.Color(102, 102, 102));
        c45.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        vistatablero.add(c45);

        c46.setBackground(new java.awt.Color(255, 255, 255));
        c46.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        vistatablero.add(c46);

        c47.setBackground(new java.awt.Color(102, 102, 102));
        c47.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        vistatablero.add(c47);

        c50.setBackground(new java.awt.Color(102, 102, 102));
        c50.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        c50.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c50ActionPerformed(evt);
            }
        });
        vistatablero.add(c50);

        c51.setBackground(new java.awt.Color(255, 255, 255));
        c51.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        vistatablero.add(c51);

        c52.setBackground(new java.awt.Color(102, 102, 102));
        c52.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        vistatablero.add(c52);

        c53.setBackground(new java.awt.Color(255, 255, 255));
        c53.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        vistatablero.add(c53);

        c54.setBackground(new java.awt.Color(102, 102, 102));
        c54.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        vistatablero.add(c54);

        c55.setBackground(new java.awt.Color(255, 255, 255));
        c55.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        vistatablero.add(c55);

        c56.setBackground(new java.awt.Color(102, 102, 102));
        c56.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        vistatablero.add(c56);

        c57.setBackground(new java.awt.Color(255, 255, 255));
        c57.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        vistatablero.add(c57);

        c60.setBackground(new java.awt.Color(255, 255, 255));
        c60.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Ficha_Peon-removebg-preview.png"))); // NOI18N
        c60.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        c60.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c60ActionPerformed(evt);
            }
        });
        vistatablero.add(c60);

        c61.setBackground(new java.awt.Color(102, 102, 102));
        c61.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Ficha_Peon-removebg-preview.png"))); // NOI18N
        c61.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        vistatablero.add(c61);

        c62.setBackground(new java.awt.Color(255, 255, 255));
        c62.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Ficha_Peon-removebg-preview.png"))); // NOI18N
        c62.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        vistatablero.add(c62);

        c63.setBackground(new java.awt.Color(102, 102, 102));
        c63.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Ficha_Peon-removebg-preview.png"))); // NOI18N
        c63.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        vistatablero.add(c63);

        c64.setBackground(new java.awt.Color(255, 255, 255));
        c64.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Ficha_Peon-removebg-preview.png"))); // NOI18N
        c64.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        vistatablero.add(c64);

        c65.setBackground(new java.awt.Color(102, 102, 102));
        c65.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Ficha_Peon-removebg-preview.png"))); // NOI18N
        c65.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        vistatablero.add(c65);

        c66.setBackground(new java.awt.Color(255, 255, 255));
        c66.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Ficha_Peon-removebg-preview.png"))); // NOI18N
        c66.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        vistatablero.add(c66);

        c67.setBackground(new java.awt.Color(102, 102, 102));
        c67.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Ficha_Peon-removebg-preview.png"))); // NOI18N
        c67.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        vistatablero.add(c67);

        c70.setBackground(new java.awt.Color(102, 102, 102));
        c70.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Torre-removebg-preview.png"))); // NOI18N
        c70.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        c70.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c70ActionPerformed(evt);
            }
        });
        vistatablero.add(c70);

        c71.setBackground(new java.awt.Color(255, 255, 255));
        c71.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Caballo-removebg-preview.png"))); // NOI18N
        c71.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        vistatablero.add(c71);

        c72.setBackground(new java.awt.Color(102, 102, 102));
        c72.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Alfil-removebg-preview.png"))); // NOI18N
        c72.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        c72.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c72ActionPerformed(evt);
            }
        });
        vistatablero.add(c72);

        c73.setBackground(new java.awt.Color(255, 255, 255));
        c73.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Reina-removebg-preview.png"))); // NOI18N
        c73.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        vistatablero.add(c73);

        c74.setBackground(new java.awt.Color(102, 102, 102));
        c74.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Rey-removebg-preview.png"))); // NOI18N
        c74.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        vistatablero.add(c74);

        c75.setBackground(new java.awt.Color(255, 255, 255));
        c75.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Alfil-removebg-preview.png"))); // NOI18N
        c75.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        vistatablero.add(c75);

        c76.setBackground(new java.awt.Color(102, 102, 102));
        c76.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Caballo-removebg-preview.png"))); // NOI18N
        c76.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        c76.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c76ActionPerformed(evt);
            }
        });
        vistatablero.add(c76);

        c77.setBackground(new java.awt.Color(255, 255, 255));
        c77.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Torre-removebg-preview.png"))); // NOI18N
        c77.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        c77.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c77ActionPerformed(evt);
            }
        });
        vistatablero.add(c77);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Tiempo negras");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 241, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 57, Short.MAX_VALUE)
        );

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("Turno");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("min:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("seg:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel5.setText("Tiempo blancas");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("min:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("seg:");

        jButton1.setText("menú");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(vistatablero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel4))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel7))))
                    .addComponent(jButton1))
                .addContainerGap(88, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(31, 31, 31)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(254, 254, 254))
                    .addComponent(vistatablero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    Wireframe w1=new Wireframe();
    w1.setVisible(true);
    this.setVisible(false);// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void c01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c01ActionPerformed
  
    }//GEN-LAST:event_c01ActionPerformed

    private void c06ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c06ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c06ActionPerformed

    private void c03ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c03ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c03ActionPerformed

    private void c02ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c02ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c02ActionPerformed

    private void c40ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c40ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c40ActionPerformed

    private void c05ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c05ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c05ActionPerformed

    private void c04ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c04ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c04ActionPerformed

    private void c20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c20ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c20ActionPerformed

    private void c07ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c07ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c07ActionPerformed

    private void c11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c11ActionPerformed

    private void c14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c14ActionPerformed

    private void c21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c21ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c21ActionPerformed

    private void c24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c24ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c24ActionPerformed

    private void c60ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c60ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c60ActionPerformed

    private void c70ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c70ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c70ActionPerformed

    private void c72ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c72ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c72ActionPerformed

    private void c77ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c77ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c77ActionPerformed

    private void c50ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c50ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c50ActionPerformed

    private void c76ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c76ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c76ActionPerformed

    private void c00ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c00ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c00ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tablero_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tablero_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tablero_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tablero_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tablero_1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton c00;
    public static javax.swing.JButton c01;
    public static javax.swing.JButton c02;
    public static javax.swing.JButton c03;
    public static javax.swing.JButton c04;
    public static javax.swing.JButton c05;
    public static javax.swing.JButton c06;
    public static javax.swing.JButton c07;
    public static javax.swing.JButton c10;
    public static javax.swing.JButton c11;
    public static javax.swing.JButton c12;
    public static javax.swing.JButton c13;
    public static javax.swing.JButton c14;
    public static javax.swing.JButton c15;
    public static javax.swing.JButton c16;
    public static javax.swing.JButton c17;
    public static javax.swing.JButton c20;
    public static javax.swing.JButton c21;
    public static javax.swing.JButton c22;
    public static javax.swing.JButton c23;
    public static javax.swing.JButton c24;
    public static javax.swing.JButton c25;
    public static javax.swing.JButton c26;
    public static javax.swing.JButton c27;
    public static javax.swing.JButton c30;
    public static javax.swing.JButton c31;
    public static javax.swing.JButton c32;
    public static javax.swing.JButton c33;
    public static javax.swing.JButton c34;
    public static javax.swing.JButton c35;
    public static javax.swing.JButton c36;
    public static javax.swing.JButton c37;
    public static javax.swing.JButton c40;
    public static javax.swing.JButton c41;
    public static javax.swing.JButton c42;
    public static javax.swing.JButton c43;
    public static javax.swing.JButton c44;
    public static javax.swing.JButton c45;
    public static javax.swing.JButton c46;
    public static javax.swing.JButton c47;
    public static javax.swing.JButton c50;
    public static javax.swing.JButton c51;
    public static javax.swing.JButton c52;
    public static javax.swing.JButton c53;
    public static javax.swing.JButton c54;
    public static javax.swing.JButton c55;
    public static javax.swing.JButton c56;
    public static javax.swing.JButton c57;
    public static javax.swing.JButton c60;
    public static javax.swing.JButton c61;
    public static javax.swing.JButton c62;
    public static javax.swing.JButton c63;
    public static javax.swing.JButton c64;
    public static javax.swing.JButton c65;
    public static javax.swing.JButton c66;
    public static javax.swing.JButton c67;
    public static javax.swing.JButton c70;
    public static javax.swing.JButton c71;
    public static javax.swing.JButton c72;
    public static javax.swing.JButton c73;
    public static javax.swing.JButton c74;
    public static javax.swing.JButton c75;
    public static javax.swing.JButton c76;
    public static javax.swing.JButton c77;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    public javax.swing.JPanel vistatablero;
    // End of variables declaration//GEN-END:variables
}
